# file: C:\Users\lxh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\exceptions.py
# hypothesis_version: 6.139.2

['AxisError', 'ComplexWarning', 'DTypePromotionError', 'TooHardError', '_is_loaded', '_msg', 'axis', 'ndim']